### ISSUE TITLE
Installation: Out of memory - any workarounds?

### ISSUE THREAD

**Issue by edrozenberg** [sonic-net/SONiC#1065]
Trying to install via ONIE on **Super Micro SSE-G3648B** (aka Celestica 1031) 48 x 1GbE switch. OOM error, and from the info I was able to search & find, it could be that the image unpack during install filled a temporary ramdisk which caused the OOM. Is there some way during the ONIE install to work around this issue, some installer params maybe? Or maybe have to use some old SONiC build that will fit (though would be unfortunate to be forced to use some very old version).

Using latest built 2022-08-20.5:
```
https://dev.azure.com/mssonic/build/_build/results?buildId=137263&view=artifacts&pathAsName=false&type=publishedArtifacts

Pipelines/Azure.sonic-buildimage.official.broadcom/20220820.5/Published artifacts

https://artprodcus3.artifacts.visualstudio.com/Af91412a5-a906-4990-9d7c-f697b81fc04d/be1b070f-be15-4154-aade-b1d3bfb17054/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zc29uaWMvcHJvamVjdElkL2JlMWIwNzBmLWJlMTUtNDE1NC1hYWRlLWIxZDNiZmIxNzA1NC9idWlsZElkLzEzNzI2My9hcnRpZmFjdE5hbWUvc29uaWMtYnVpbGRpbWFnZS5icm9hZGNvbQ2/content?format=file&subpath=/target/sonic-broadcom.bin
```

Install error:
```
...
...
0 pages in swap cache
Swap cache stats: add 0, delete 0, find 0/0
Free swap  = 0kB
Total swap = 0kB
522224 pages RAM
13485 pages reserved
213 pages shared
504878 pages non-shared
Out of memory: Kill process 1178 (tar) score 1 or sacrifice child
Killed process 1178 (tar) total-vm:7552kB, anon-rss:88kB, file-rss:256kB

To check the install status inspect /var/log/onie.log.
Try this:  tail -f /var/log/onie.log
```

I mounted a USB stick partition (/dev/sdb1) to /tmp/mnt and attempted to install that image
```
ONIE:/mnt/tmp # ls -l
drwx------    2 root     0            16384 Aug 21  2022 lost+found
-rw-r--r--    1 root     0        1033002898 Aug 21  2022 sonic-broadcom.bin
-rw-r--r--    1 root     0              716 Aug 21  2022 sonic-broadcom.bin.txt

ONIE:/mnt/tmp # df -h
Filesystem                Size      Used Available Use% Mounted on
tmpfs                    10.0M     24.0K     10.0M   0% /run
tmpfs                    10.0M         0     10.0M   0% /run/lock
tmpfs                   993.6M         0    993.6M   0% /tmp
tmpfs                   993.6M         0    993.6M   0% /var/tmp
tmpfs                   993.6M         0    993.6M   0% /run/shm
/dev/sda2               124.0M     15.8M    101.8M  13% /mnt/onie-boot
/dev/sdb1               112.8G      1.0G    106.0G   1% /mnt/tmp
```

**Comment by Blueve** [comment]
201811 image should works good with this switch.

If you want to use 202012 image, then I would like to suggest you only include required features in your image (public built image include almost all features and that will can increase the image size)

Another workaround is to create a SWAP space before do the installation (i haven't tried add swap in ONIE... but it is worth to have a try).

Or you can install 201811 image, then upgrade to 202012. We have a feature which will create swap automatically if total_mem is too low in sonic_installer.

**Comment by edrozenberg** [comment]
@Blueve thank you for your suggestions. After 15 hours of work I give up for now trying to install SONiC on these crap old switches. There was no `swap` command on the old onie version, so I spent a day building a new onie image for the switch. The switch only supports old (USB2 I guess) sticks, so I tried setting up swap on that and got sector errors. SONiC image links on the SONiC wiki are broken and trying to find anything on the Azure pipelines pages is horribly difficult - I had to use the bad broken broadcom link from the SONiC wiki and modify what I could find on Azure to manage to download a recent image. I have no idea where to try finding the images you mention. Maybe I'll try again with SONiC if I buy some more recent switch in the future. This stuff is for experts only and there's very little troubleshooting public info available since so few people are using it.

**Comment by Blueve** [comment]
@edrozenberg you can check our newest images by clicking the badge in https://github.com/sonic-net/sonic-buildimage README.md
e.g. latest 202012: https://dev.azure.com/mssonic/build/_build/results?buildId=137582&view=results
I just notice that 201811 build pipeline has been paused, you might need build the image manually : (

SONiC is designed for Cloud which means it is sometimes not `user friendly` , but it is also an open community and you are welcome to make improvements on code/doc/test : D

**Comment by edrozenberg** [comment]
Thanks for the links that helps, I did find that path via the Azure pipelines eventually, but I had no idea I could click on the color badges for the platform.

The build download links (zip) don't work, they download multiple GB's and still not finished - should be only ~1GB. I looked at the old broken links on the SONiC wiki and have to manually modify the build download with the ending `content?format=file&subpath=/target/sonic-broadcom.bin` instead of `zip`.

I've been doing Linux admin for a few decades, and devops for a few years, but even so as a new user to SONiC it's so far impossible to install an image on my (old crappy) hardware but which is on the supported hardware list. I assume/hope a new switch like the EdgeCore 7326 would have enough memory to deal with recent build images.

Happy to help, open source is "your code contributions are welcome!" I totally get it, but as I know nothing about SONiC yet and can't install it, fixing Azure pipelines, updating the hardware compatibility list, and figuring out which build versions work with which hardware to be fair is not something I can jump into.

Suggestions on what would be a massive help to new users:
* Hardware compatibility list that is maintained - the current one is 2021-11-25:
```
https://github.com/Azure/SONiC/wiki/Supported-Devices-and-Platforms  >>>
https://github.com/sonic-net/SONiC/wiki/Supported-Devices-and-Platforms >>>
NOTE: This page is updated manually once in a while and hence may not be pointing to the latest MASTER image. The current links are based on successful builds as on 25thNov2021 . To get the latest master image, refer pipelines page.
```

* A matrix of supported hardware and direct links to the latest binary image that is known to work on that hardware. If some hardware is considered obsolete crap nobody should use, remove the hardware from the compat list so nobody spends money to buy some and try to use it for a learning lab (like me :) )

If I can help in some way, let me know what I can do as a new user.


In more detail, documenting below the most likely "new user experience path", based on best effort, reading the docs, looking in all the right places:

https://github.com/Azure/SONiC/wiki/Supported-Devices-and-Platforms  >>>

https://github.com/sonic-net/SONiC/wiki/Supported-Devices-and-Platforms >>>

**NOTE: This page is updated manually once in a while and hence may not be pointing to the latest MASTER image. The current links are based on successful builds as on 25thNov2021 . To get the latest master image, refer pipelines page.**

?

Broadcom links all broken:
(https://artprodcus3.artifacts.visualstudio.com/Af91412a5-a906-4990-9d7c-f697b81fc04d/be1b070f-be15-4154-aade-b1d3bfb17054/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zc29uaWMvcHJvamVjdElkL2JlMWIwNzBmLWJlMTUtNDE1NC1hYWRlLWIxZDNiZmIxNzA1NC9idWlsZElkLzUxMjU1L2FydGlmYWN0TmFtZS9zb25pYy1idWlsZGltYWdlLmJyb2FkY29t0/content?format=file&subpath=/target/sonic-broadcom.bin)

Links show:
```
{"$id":"1","innerException":null,"message":"The requested build 51255 could not be found.","typeName":"System.ArgumentException, mscorlib","typeKey":"ArgumentException","errorCode":0,"eventId":0}
```

**"Refer pipelines page":**

https://sonic-build.azurewebsites.net/ui/sonic/Pipelines

**Click** broadcom master "Azure.sonic-buildimage.official.broadcom" >>>
**Click** Releases: Nothing
**Click** Artifacts: "Connect to the feed to get started"   ?
**Click** back to Pipelines: now shows "Recently run pipelines"
**Back,back,back,** or Start over from the sonic page
**Click** the run 20220821.5 (green checkmarked)
Where is the image? I see only build sources which goes back to GitHub

On GitHub build sources, if you're lucky, you figure out the link to click. Then, clicking the link gives:

https://artprodcus3.artifacts.visualstudio.com/Af91412a5-a906-4990-9d7c-f697b81fc04d/be1b070f-be15-4154-aade-b1d3bfb17054/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zc29uaWMvcHJvamVjdElkL2JlMWIwNzBmLWJlMTUtNDE1NC1hYWRlLWIxZDNiZmIxNzA1NC9idWlsZElkLzEzNzY0MS9hcnRpZmFjdE5hbWUvc29uaWMtYnVpbGRpbWFnZS5icm9hZGNvbQ2/content?format=zip

This downloads "something" forever (I stopped it after 10 GB)

Then you need to change the end of the url as follows, if you're clever enough to look at the structure of the links back to the supported hardware page links:

`format=file&subpath=/target/sonic-broadcom.bin` instead of `zip`.

**Comment by edrozenberg** [comment]
I'll have to figure out how to build my own img and leave out all the unnecessary stuff.

Tried the 201911 build (600MB+) because it's smaller than the others, but after it finished (I guess), the boot screen shows only "Welcome to GRUB", no way to continue, and I had to use the Super Micro ONIE restore guide (https://www.supermicro.com/support/faqs/faq.cfm?faq=32384) with the custom ONIE recovery image I had built myself earlier (onie-recovery-x86_64-cel_e1031-r0.iso) to restore ONIE from scratch and get ONIE working again. Sucky sucky experience all the way. Not blaming anyone. Just no fun and no results yet.

**Comment by edrozenberg** [comment]
Related - https://github.com/sonic-net/SONiC/issues/174

That user ran into the same exact issue with the SONiC installation img borking his ONIE back in 2018, requiring ONIE recovery.

**Comment by mariusleu** [comment]
I was able to successfully install `201811` on my SSE-G3648B, as suggested by @Blueve 

The image can be downloaded at this url:

https://sonic-build.azurewebsites.net/api/sonic/artifacts?branchName=201811&platform=broadcom&target=target%2Fsonic-broadcom.bin

(If you need to download other version, just replace the branchName in the URL above)

FYI @edrozenberg
