### ISSUE TITLE
Next hop group with a single next hop is creating a nexthop group on ASIC_DB.

### ISSUE THREAD

**Issue by f-agnes** [sonic-net/SONiC#1100]
According to documentation: [next hop group hld](https://github.com/sonic-net/SONiC/blob/master/doc/ip/next_hop_group_hld.md) it's possible to have next hop group configured with a single next hop or multiple next hop. When configured with a single next hop the documentation say that orchagent will simply get the SAI identifier for that next hop from the neighbor orchagent and if the group has multiple next hops, the next hop group orchagent will add a next hop group to ASIC_DB and then add a next hop group member to ASIC_DB for every member of that group that is available to be used.

However, when testing adding an entry with a single next hop on next hop group table the orchagent is creating an NEXT_HOP_GROUP type ECMP on ASIC_DB.
For example, running the following script:
```
admin@sonic:~$ cat test.py
from swsscommon import swsscommon

key = "test1"
pairs = {"nexthop": "10.0.2.3", "ifname": "Ethernet8"}

db = swsscommon.DBConnector("APPL_DB", 0, True)
tbl = swsscommon.ProducerStateTable(db, "NEXTHOP_GROUP_TABLE")
fvs = swsscommon.FieldValuePairs(list(pairs.items()))
tbl.set(key, fvs)
```
I get the following database entries:
```
admin@sonic:~$ sonic-db-cli ASIC_DB keys \*NEXT\*

admin@sonic:~$ sonic-db-cli APPL_DB keys \*NEXT\*

admin@sonic:~$ python test.py
admin@sonic:~$ sonic-db-cli APPL_DB keys \*NEXT\*
NEXTHOP_GROUP_TABLE:test1
admin@sonic:~$ sonic-db-cli ASIC_DB keys \*NEXT\*
ASIC_STATE:SAI_OBJECT_TYPE_NEXT_HOP:oid:0x4000000000bdd
ASIC_STATE:SAI_OBJECT_TYPE_NEXT_HOP_GROUP:oid:0x5000000000bde
ASIC_STATE:SAI_OBJECT_TYPE_NEXT_HOP_GROUP_MEMBER:oid:0x2d000000000bdf
admin@sonic:~$ sonic-db-cli ASIC_DB hgetall "ASIC_STATE:SAI_OBJECT_TYPE_NEXT_HOP:oid:0x4000000000bdd"
{'SAI_NEXT_HOP_ATTR_TYPE': 'SAI_NEXT_HOP_TYPE_IP', 'SAI_NEXT_HOP_ATTR_IP': '10.0.2.3', 'SAI_NEXT_HOP_ATTR_ROUTER_INTERFACE_ID': 'oid:0x6000000000bc1'}
admin@sonic:~$ sonic-db-cli ASIC_DB hgetall "ASIC_STATE:SAI_OBJECT_TYPE_NEXT_HOP_GROUP:oid:0x5000000000bde"
{'SAI_NEXT_HOP_GROUP_ATTR_TYPE': 'SAI_NEXT_HOP_GROUP_TYPE_DYNAMIC_UNORDERED_ECMP'}
admin@sonic:~$ sonic-db-cli ASIC_DB hgetall "ASIC_STATE:SAI_OBJECT_TYPE_NEXT_HOP_GROUP_MEMBER:oid:0x2d000000000bdf"
{'SAI_NEXT_HOP_GROUP_MEMBER_ATTR_NEXT_HOP_GROUP_ID': 'oid:0x5000000000bde', 'SAI_NEXT_HOP_GROUP_MEMBER_ATTR_NEXT_HOP_ID': 'oid:0x4000000000bdd'}
admin@sonic:~$
```
Is it correct to have a next hop group created on ASIC_DB for a single next hop configured on NEXTHOP_GROUP_TABLE?

The test was performed using the sonic version:
SONiC Software Version: SONiC.master.156846-1f0699f51

**Comment by prsunny** [comment]
Please create issues under sonic-buildimage in future. Yes, it is expected to have a NGH with single nexthop as addition and deletion of nexthops handling can be simplified.

**Comment by f-agnes** [comment]
Hi @prsunny,

Thank you for your answer.

I think the Next Hop Group HLD documentation needs some updates but for that I can open a new issue under sonic-buildimage project.

Closing this issue.
