### ISSUE TITLE
SSH global config

### ISSUE THREAD

**Issue by Yuval-Mellanox** [sonic-net/SONiC#1169]
We introduce a procedure to configure ssh server global settings. 
This feature will include 3 configurations in the first phase, but can be extended easily to include additional configurations.

**Comment by XioNoX** [comment]
I might be too late, but would it be possible to add options to disable root/admin logging, as well as disable password logging (to rely on SSH keys only)?
Thanks

**Comment by ycoheNvidia** [comment]
> I might be too late, but would it be possible to add options to disable root/admin logging, as well as disable password logging (to rely on SSH keys only)? If it's too late, what would be the best way to suggest it as feature request? Thanks

These arguments were not part of our feature's scope. Since the feature is already merged you are welcome to add the support yourself and we would be happy to help you with the review
