### ISSUE TITLE
Preserve CoPP table during fastboot

### ISSUE THREAD

**Issue by Yuval-Mellanox** [sonic-net/SONiC#1174]
Preserving the contents of the CoPP (Sonic Control Plane Policing) tables during reboot for faster LAG creation in order to improve fast-reboot's dataplane downtime

**Comment by zhangyanzhao** [comment]
HLD #1107  is reviewed in community on 1/3/2023

**Comment by zhangyanzhao** [comment]
1107 and code PRs are merged
