### ISSUE TITLE
Auto tech support w/orchagent abort case

### ISSUE THREAD

**Issue by Yuval-Mellanox** [sonic-net/SONiC#1175]
it is highly likely that by the time auto-techsupport collects saisdkdump, syncd might have been restarted or in the process of restarting. In either case, we'd be loosing the saisdkdump information before restart which will contain useful information for triaging. Thus, a special handling is needed for the core dumps generated from swss container

**Comment by zhangyanzhao** [comment]
https://github.com/sonic-net/SONiC/pull/1212 and code PRs are merged
