### ISSUE TITLE
Images Download

### ISSUE THREAD

**Issue by jimthedj65** [sonic-net/SONiC#1214]
Hi All,

Trying to download an image for my Arista 7170 64c has this moved to another location under LFS?

The links here seem to time out?

Thanks for any assistance.

**Comment by jimthedj65** [comment]
can anyone help where to get the download images from?

**Comment by jimthedj65** [comment]
the live url for downloading arista images appears to be 
[[sonic_image_md_update](https://github.com/sonic-net/SONiC/blob/sonic_image_md_update/supported_devices_platforms.md)](url)  

and not 

https://sonic-build.azurewebsites.net/api/sonic/artifacts?branchName=master&platform=barefoot&buildId=50092&target=target%2Fsonic-aboot-barefoot.swi

**Comment by ronnievsmith** [comment]
https://sonic-build.azurewebsites.net has been unavailable for me a few times. It's offline now.
