### ISSUE TITLE
P4-CLI

### ISSUE THREAD

**Issue by zhangyanzhao** [sonic-net/SONiC#1238]

**Comment by zhangyanzhao** [comment]
no update, move to backlog

**Comment by bhagatgit** [comment]
This PR  was opened for submitting P4RT tables in the DB. 
@mint570 
Can you add more details in this issue and point to the code PRs that were used for submission. Thank you.

**Comment by mint570** [comment]
This pr, https://github.com/sonic-net/sonic-utilities/pull/2773, adds the CLI functionality to show the P4RT tables.
