### ISSUE TITLE
gNMI Master Arbitration

### ISSUE THREAD

**Issue by zhangyanzhao** [sonic-net/SONiC#1240]

**Comment by sallylsy** [comment]
Master Arbitration pull-request is out for review. https://github.com/sonic-net/SONiC/pull/1285

**Comment by sallylsy** [comment]
Hi @zhangyanzhao, I cannot add any reviewer for the PR. I wonder if you can pick up the PR and review it, or I need to reach out other people. Thanks!

**Comment by zhangyanzhao** [comment]
merged in 202311
