### ISSUE TITLE
Show ip bgp summary output needs proper alignment

### ISSUE THREAD

**Issue by mfriyas** [sonic-net/SONiC#125]
Device S6000 was loaded with sonic and having T0 minigraph configurations. Wile issuing show ip bgp summary command, output display was not in a proper format.

root@sonic-s6000-02:/home/admin# show ip bgp sum
Command: sudo vtysh -c "show ip bgp summary"
BGP router identifier 10.1.0.32, local AS number 65100
RIB entries 12810, using 1401 KiB of memory
Peers 8, using 36 KiB of memory
Peer groups 2, using 112 bytes of memory

Neighbor        V             AS MsgRcvd MsgSent   TblVer  InQ OutQ Up/Down  State/PfxRcd
10.0.0.57       4 64600   17209   18223        0    0    0 12:18:09     6402
10.0.0.59       4 64600   17208   15025        0    0    0 12:23:12     6402
10.0.0.61       4 64600   26822   37428        0    0    0 12:27:57     6402
10.0.0.63       4 64600   17209   31009        0    0    0 12:13:34     6402
                        >>>>>>>>>>>
Total number of neighbors 4

BGP AS no column was attached with version .

**Comment by stcheng** [comment]
i think that is a Quagga issue (or a 'design').

**Comment by pavel-shirshov** [comment]
it's the quagga issue
See https://github.com/Azure/sonic-quagga/blob/df6b70902b4c29447ac52277cf6d5b7f6abca71e/bgpd/bgp_vty.c#L7211
and 
https://github.com/Azure/sonic-quagga/blob/df6b70902b4c29447ac52277cf6d5b7f6abca71e/bgpd/bgp_vty.c#L7278
