### ISSUE TITLE
IPv6 RS & NS packets (ICMPv6 type 133 & 135) create a loop in L2 MC-LAG scenario

### ISSUE THREAD

**Issue by pliviu** [sonic-net/SONiC#1253]
**Problem Summary:**
A loop is created when an ICMPv6 router solicitation or neighbor solicitation packet is sent on an mclag L2 link (see the diagram attached).

**Note:**
Although the isolation group on Switch 2 / SONiC includes interface PO1, the v6 packet is sent back by Switch 2 / SONiC to L2 switch and create a loop (L2 switch sees on interface PO1 the exact same packet he sent). All the IPv4 broadcasts like ARPs are not sent back on PO1, only ICMPv6 router solicitation or neighbor solicitation packets.

**Workaround:**
Remove neigh_discovery from COPP_TRAP in /etc/sonic/copp_cfg.json. Apparently neigh_discovery packets are "copied" and that somehow bypass isolation group in L2 MC-LAG scenarios. There is no issue with IPv4 ARP packets.

            "arp": {
                    "trap_ids": "arp_req,arp_resp,neigh_discovery",
                    "trap_group": "queue4_group2",
                    "always_enabled": "true"
            },
            
                        "queue4_group2": {
                    "trap_action":"copy", <<<<<<<<<<< here

**Diagram:**
<img width="562" alt="v6loop_topology" src="https://user-images.githubusercontent.com/7489314/216688601-9ef7429d-99f5-451c-872c-908b93b39a45.png">

**Comment by venkatmahalingam** [comment]
@pliviu A loop is created when an ICMPv6 router solicitation or neighbor solicitation packet is sent on an mclag L2 link
Is this loop created due to ICMPv6 packets forwarding via L2 MC-LAG in kernel?

**Comment by pliviu** [comment]
I think so, because i see the those ICMPv6 packet in kernel ... and because they are in kernel bypass isolation groups from asic (at least this is what i suppose).

**Comment by venkatmahalingam** [comment]
The commit looks good to me, I believe, we just need to add ip6tables rules in the kernel to prevent forwarding the ICMP6 packets that are destined for CPU only.

**Comment by pliviu** [comment]
I didn't succed fixing this issue by filtering with ip6tables. I even disabled IPv6 for good, the loop is still there.
The question here is why ICMPv6 type 133 & 135 are sent to the kernel in the first place. I see no IPv4 broadcast like ARP on tcpdump but those ICMPv6 packets. More then that, on Switch 1 i see one packet and on Switch 2 i see two packets ... the packet is duplicated somehow.

**Comment by pliviu** [comment]
Yes, the issue is solved with this rule only:
sudo /sbin/ebtables -A FORWARD -p 802_1Q --vlan-encap IPv6 -j DROP

**Comment by venkatmahalingam** [comment]
Cool, forgot to mention about ebtables, the bridge/VLAN level forwarding should be controlled with ebtables only. Make sure we dont have any use-case for soft forwarding ICMPv6 packets at the kernel level.
