### ISSUE TITLE
NTP: Additional NTP configuration knobs + NTP server provisioning

### ISSUE THREAD

**Issue by Yuval-Mellanox** [sonic-net/SONiC#1254]
NTP servers will support the next configurations:
•	Changing the protocol version
•	Setting security key
•	Changing aggressive mode (iburst)
•	Enabling/disabling the configured server
NTP feature global config will support the next feature:
•	Key management
•	Enable/dis NTP authentication
•	Enable/dis NTP feature

**Comment by zhangyanzhao** [comment]
merged into 202311 release
