### ISSUE TITLE
UMF Transformer Enhancements and Optimization

### ISSUE THREAD

**Issue by jeff-yin** [sonic-net/SONiC#1330]
Transformer infrastructure -- memory, CRUD/GET operation optimizations, UT. This is a dependency for UMF Subscription support being contributed by Broadcom. This entry was opened to account for Dell's portion of the contribution toward UMF Subscription; it uses the same parent PR as the "UMF Subscription Infra (#1191)" project. 

Code PRs:

| Repo	| PR title	| State |
|----------|------------|-----------|
| sonic-mgmt-common  | [Apply goyang patch xfmr memory optimization](https://github.com/sonic-net/sonic-mgmt-common/pull/79)	| Open |
|   | [Transformer Infra memory optimization and enhancements](https://github.com/sonic-net/sonic-mgmt-common/pull/80) | Open |
|  | [Transformer Infra Unit Tests](https://github.com/sonic-net/sonic-mgmt-common/pull/81) |  Open |

**Comment by zhangyanzhao** [comment]
@jeff-yin  can you please help to add Transformer Infra UT PR to https://github.com/sonic-net/SONiC/pull/1287?

**Comment by zhangyanzhao** [comment]
HLD and code PRs are merged. Close this as done.
