### ISSUE TITLE
LDAP support

### ISSUE THREAD

**Issue by Yuval-Mellanox** [sonic-net/SONiC#1387]

**Comment by liat-grozovik** [comment]
@zhangyanzhao this one should be deleted. it was decided not to move forward with this feature moving forward.

**Comment by liat-grozovik** [comment]
@zhangyanzhao in the github project we have this entry as well as the HLD as a different entry.
we should have this one only and it is already pointing to the right hld
https://github.com/sonic-net/SONiC/pull/1487

can you please clean it?
