### ISSUE TITLE
UEFI key management in SONiC to perform secure boot key rotation, update, remove revoke etc

### ISSUE THREAD

**Issue by zhangyanzhao** [sonic-net/SONiC#1401]

**Comment by sacnaik** [comment]
https://github.com/sonic-net/SONiC/pull/1451

**Comment by zhangyanzhao** [comment]
moved to 202405

**Comment by zhangyanzhao** [comment]
added to 202411 release per Cisco ask.

**Comment by zhangyanzhao** [comment]
use https://github.com/sonic-net/SONiC/pull/1451 to track and close this issue.
