### ISSUE TITLE
Fpmsyncd Next Hop Table Enhancement

### ISSUE THREAD

**Issue by zhangyanzhao** [sonic-net/SONiC#1410]

**Comment by nakano-omw** [comment]
@zhangyanzhao I would like to see "Fpmsyncd Next Hop Table Enhancement" added to the 202405 release list. 
https://github.com/orgs/sonic-net/projects/17/views/1

**Comment by nakano-omw** [comment]
Here's a link to the PR. https://github.com/sonic-net/SONiC/pull/1425

**Comment by zhangyanzhao** [comment]
added to 202405 release with the HLD PR.

**Comment by zhangyanzhao** [comment]
will use HLD PR to track this feature for future release. Close this tracking issue.
