### ISSUE TITLE
Build improvements changes

### ISSUE THREAD

**Issue by Yuval-Mellanox** [sonic-net/SONiC#1413]
The idea is to split the build_debian.sh into two stages:

 

    Stage 1 (first half of build_debian.sh) Do all the needed preparation (debootstrap, apt-install, etc.).

Save the rootfs into a temporary squashfs file.

    Stage 2 (second half of build_debian.sh). Continue the build from the point where the previous step finished (via loading the temporary squashfs as rootfs).

Install all the dependencies (sonic_debian_extension.sh) and finish the build.

**Comment by liat-grozovik** [comment]
Following an offline discussion with BRCM who have PR in parallel it was agreed to move with Nvidia approach
@Yakiv-Huryk will provide PR for HLD, no need for community review @adyeung will assign someone from BRCM to review it.

**Comment by zhangyanzhao** [comment]
merged in 202311 release
