### ISSUE TITLE
[Template] Working Group Creation - Do Not Close

### ISSUE THREAD

**Issue by lucyhyde** [sonic-net/SONiC#1503]
### Click EDIT to copy/paste the following items to a new GitHub Issue and assign Lucy Hyde (@lucyhyde) and any other needed members. Please use the "working group onboarding" label.

**Working Group Details**

**--Working Group Name:**
**--Working Group Presenter (name and email):**
**--TSC Approval Date:**
**--Presentation Files (if applicable):**

**Mailing List**

* [ ] (PM) Create mailing list in groups.io 
* [ ] (PM/WG) Configure settings as appropriate (WG, please select the following features):
    * [ ] Wiki
    * [ ] Calendar
    * [ ] Files
    * [ ] Directory
    * [ ] Database
    * [ ] Polls
* [ ] (PM) Import necessary working group contacts and set the following members as owners of mailing list
    * [ ] Owner Name/GitHub ID:
    * [ ] Owner Name/GitHub ID:
    * [ ] Owner Name/GitHub ID:

**Zoom**

* [ ] (PM) Share credentials with primary/alternate
    * [ ] Name/GitHub ID:
    * [ ] Name/GitHub ID:

**Calendar**

* [ ] (PM) Share credentials with primary/alternate
    * [ ] Name/GitHub ID:
    * [ ] Name/GitHub ID:

**Other**
_Please insert any other needs of the working group using the following empty bullet points and assign as appropriate_
* [ ] (PM/WG) 
* [ ] (PM/WG)
* [ ] (PM/WG)

**Comment by lguohan** [comment]
@lucyhyde , i created a issue template and simplified the workflow, updated the wiki. this template is no longer needed.
