### ISSUE TITLE
SAI  health monitor and dump generation

### ISSUE THREAD

**Issue by Yuval-Mellanox** [sonic-net/SONiC#1511]
SAI monitoring feature, describes behavior when SAI get stuck, NOS notifications and also changes concerning dump, health notification, shutdown and syslog depending on severity of occurred events.

**Comment by stephenxs** [comment]
https://github.com/sonic-net/SONiC/pull/1533

**Comment by zhangyanzhao** [comment]
Community reviewed on 12/12/2023

**Comment by zhangyanzhao** [comment]
HLD and code PRs are merged and close this tracking issue.
