### ISSUE TITLE
Extend CMIS host management debug capability

### ISSUE THREAD

**Issue by Yuval-Mellanox** [sonic-net/SONiC#1536]

**Comment by keboliu** [comment]
https://github.com/sonic-net/SONiC/pull/1476
https://github.com/sonic-net/SONiC/pull/1516
https://github.com/sonic-net/SONiC/pull/1522

**Comment by keboliu** [comment]
@liat-grozovik we still have https://github.com/sonic-net/SONiC/pull/1522 WIP
