### ISSUE TITLE
Power over Ethernet (PoE)

### ISSUE THREAD

**Issue by zhangyanzhao** [sonic-net/SONiC#1539]

**Comment by zhangyanzhao** [comment]
Taras Chornyi from PLVision proposed this feature. https://github.com/sonic-net/SONiC/pull/1508 was proposed to community in 202311 release, better to check the overlap and aligned.

**Comment by taraschornyiplv** [comment]
Design PR https://github.com/sonic-net/SONiC/pull/1631

**Comment by zhangyanzhao** [comment]
code PR is not ready, move to backlog.

**Comment by matiAlfaro** [comment]
@zhangyanzhao - can you move to 202411?
Code PRs can be found at - https://github.com/sonic-net/sonic-buildimage/pull/19636

**Comment by zhangyanzhao** [comment]
use https://github.com/sonic-net/SONiC/pull/1631 and https://github.com/sonic-net/sonic-buildimage/pull/19636 to track. close this issue.
