### ISSUE TITLE
SONiC container upgrade to Bookworm (Debian 12)

### ISSUE THREAD

**Issue by zhangyanzhao** [sonic-net/SONiC#1541]

**Comment by zhangyanzhao** [comment]
This needs community help to upgrade different dockers.

**Comment by saiarcot895** [comment]
| Container  | PR | PR Status |
| ------------- | ------------- | ------------- |
| base  | sonic-net/sonic-buildimage#17742 | ![Bookworm Base Layer PR](https://img.shields.io/github/pulls/detail/state/sonic-net/sonic-buildimage/17742) |
| config-engine  | sonic-net/sonic-buildimage#17742 | ![Bookworm Config Engine Layer PR](https://img.shields.io/github/pulls/detail/state/sonic-net/sonic-buildimage/17742) |
| swss-layer  | sonic-net/sonic-buildimage#18062 | ![Bookworm SWSS Layer PR](https://img.shields.io/github/pulls/detail/state/sonic-net/sonic-buildimage/18062) |
| database  | sonic-net/sonic-buildimage#18108 | ![Bookworm Database PR](https://img.shields.io/github/pulls/detail/state/sonic-net/sonic-buildimage/18108) |
| teamd  | sonic-net/sonic-buildimage#18108 | ![Bookworm Teamd PR](https://img.shields.io/github/pulls/detail/state/sonic-net/sonic-buildimage/18108) |
| radv  | sonic-net/sonic-buildimage#18108 | ![Bookworm RADV PR](https://img.shields.io/github/pulls/detail/state/sonic-net/sonic-buildimage/18108) |
| swss  | sonic-net/sonic-buildimage#18342 | ![Bookworm SWSS PR](https://img.shields.io/github/pulls/detail/state/sonic-net/sonic-buildimage/18342) |
| snmp  | sonic-net/sonic-buildimage#18150 | ![Bookworm SNMP PR](https://img.shields.io/github/pulls/detail/state/sonic-net/sonic-buildimage/18150) |
| lldp  | sonic-net/sonic-buildimage#18150 | ![Bookworm LLDP PR](https://img.shields.io/github/pulls/detail/state/sonic-net/sonic-buildimage/18150) |
| frr/bgp  | sonic-net/sonic-buildimage#18233 | ![Bookworm FRR/BGP PR](https://img.shields.io/github/pulls/detail/state/sonic-net/sonic-buildimage/18233) |
| dhcp-relay  | sonic-net/sonic-buildimage#17783 | ![Bookworm DHCP-Relay PR](https://img.shields.io/github/pulls/detail/state/sonic-net/sonic-buildimage/17783) |
| macsec  | sonic-net/sonic-buildimage#18148 | ![Bookworm MACSec PR](https://img.shields.io/github/pulls/detail/state/sonic-net/sonic-buildimage/18148) |
| sflow  | sonic-net/sonic-buildimage#18543 | ![Bookworm Sflow PR](https://img.shields.io/github/pulls/detail/state/sonic-net/sonic-buildimage/18543) |
| telemetry  | sonic-net/sonic-buildimage#18548 | ![Bookworm Telemetry PR](https://img.shields.io/github/pulls/detail/state/sonic-net/sonic-buildimage/18548) |
| gnmi  | sonic-net/sonic-buildimage#18548 | ![Bookworm GNMI PR](https://img.shields.io/github/pulls/detail/state/sonic-net/sonic-buildimage/18548) |
| eventd  | sonic-net/sonic-buildimage#18557 | ![Bookworm Eventd PR](https://img.shields.io/github/pulls/detail/state/sonic-net/sonic-buildimage/18557) |
| mux  | sonic-net/sonic-buildimage#18310 | ![Bookworm Mux PR](https://img.shields.io/github/pulls/detail/state/sonic-net/sonic-buildimage/18310) |
| syncd (VS)  | sonic-net/sonic-buildimage#18347 | ![Bookworm Syncd (VS) PR](https://img.shields.io/github/pulls/detail/state/sonic-net/sonic-buildimage/18347) |
| syncd (Broadcom)  | Deferred to 202411 |  |
| syncd (Mellanox)  | sonic-net/sonic-buildimage#18651 | ![Bookworm Syncd (Mellanox) PR](https://img.shields.io/github/pulls/detail/state/sonic-net/sonic-buildimage/18651) |
| syncd (Marvell)  | sonic-net/sonic-buildimage#18740 | ![Bookworm Syncd (Marvell) PR](https://img.shields.io/github/pulls/detail/state/sonic-net/sonic-buildimage/18740) |
| pmon  | sonic-net/sonic-buildimage#18291 | ![Bookworm PMON PR](https://img.shields.io/github/pulls/detail/state/sonic-net/sonic-buildimage/18291) |
| mgmt-framework  | sonic-net/sonic-buildimage#18548 | ![Bookworm MGMT Framework PR](https://img.shields.io/github/pulls/detail/state/sonic-net/sonic-buildimage/18548) |
| nat  | sonic-net/sonic-buildimage#18799 | ![Bookworm NAT PR](https://img.shields.io/github/pulls/detail/state/sonic-net/sonic-buildimage/18799) |
| iccpd  | sonic-net/sonic-buildimage#18542 | ![Bookworm ICCPD PR](https://img.shields.io/github/pulls/detail/state/sonic-net/sonic-buildimage/18542) |

**Comment by zhangyanzhao** [comment]
HLD and code PRs are merged and close this tracking issue.
