### ISSUE TITLE
Enhance communication channel between FRR and SONiC

### ISSUE THREAD

**Issue by cscarpitta** [sonic-net/SONiC#1564]
Currently FRR is not able to send SRv6 SIDs and Policies to SONiC. This feature will extend the communication channel between FRR and SONiC to address this gap.

**Comment by zhangyanzhao** [comment]
HLD is not ready yet, move to backlog.

**Comment by zhangyanzhao** [comment]
duplicated with 1620. Close this tracking issue and use 1620 to track
