### ISSUE TITLE
Upgrade to FRR 10.0.1

### ISSUE THREAD

**Issue by cscarpitta** [sonic-net/SONiC#1565]
| Module name  | PR  | State |
| ------------- | ------------- | ----|
| [sonic-buildimage](https://github.com/sonic-net/sonic-buildimage) | [FRR upgrade to 10.0.1](https://github.com/sonic-net/sonic-buildimage/pull/20269) | ![GitHub issue/pull request detail](https://img.shields.io/github/pulls/detail/state/sonic-net/sonic-buildimage/20269) | 
| [sonic-mgmt](https://github.com/sonic-net/sonic-mgmt) | [Remove depreciated test code](https://github.com/sonic-net/sonic-mgmt/pull/15691) | ![GitHub issue/pull request detail](https://img.shields.io/github/pulls/detail/state/sonic-net/sonic-mgmt/15691) |

**Comment by zhangyanzhao** [comment]
@cscarpitta  FRR upgrade has an agreed process to follow, see #1438 . For 202405 release, Nvidia owns that upgrade to 8.5.4, see #1537 . Can you please check with Nvidia to see how to align? version x.y.z is SONiC preferred version. Thanks.

**Comment by zhangyanzhao** [comment]
Move to post 202405 per discussion with Cisco. Thanks.

**Comment by Yuval-Mellanox** [comment]
@zhangyanzhao @cscarpitta 
can you please add this to 2024-11 tracker?
https://github.com/orgs/sonic-net/projects/18/views/1

**Comment by hasan-brcm** [comment]
@sudhanshukumar22 from brcm will take care of upgrading FRR to v9.1. The effort will start around mid July. If a 9.1.x minor FRR version available by that time, it will be used for the upgrade. Otherwise, 9.1.

**Comment by Yuval-Mellanox** [comment]
@hasan-brcm  Thanks.
please make sure it is part of the 2024-11 tracker - https://github.com/orgs/sonic-net/projects/18/views/1

**Comment by hasan-brcm** [comment]
> @hasan-brcm Thanks. please make sure it is part of the 2024-11 tracker - https://github.com/orgs/sonic-net/projects/18/views/1
Updated the tracker.
