### ISSUE TITLE
Test Plan for OSPF and BFD

### ISSUE THREAD

**Issue by zhangyanzhao** [sonic-net/SONiC#1576]
1. Test Plan for OSPF & Test cases 
2. TestPlan for BFD 
3. Test Plan for OSPF Peers Monitoring using BFD along with test cases 
4. Test Plan for OSPFv3 Peers Monitoring using BFD along with test cases

**Comment by ridahanif96** [comment]
@zhangyanzhao Thanks for adding these issues. 
Please add [Asad](https://github.com/asraza07) assignee for these testplan HLDs.

**Comment by zhangyanzhao** [comment]
HLD is not ready yet, move to backlog.

**Comment by ridahanif96** [comment]
Test Plans HLD presented in Test sub group and merged 
https://github.com/sonic-net/sonic-mgmt/pull/11898
https://github.com/sonic-net/sonic-mgmt/pull/11241
https://github.com/sonic-net/sonic-mgmt/pull/11899
