### ISSUE TITLE
NetScan over VLAN support

### ISSUE THREAD

**Issue by zhangyanzhao** [sonic-net/SONiC#1608]

**Comment by bingwang-ms** [comment]
The HLD is working in progress. Will have it reviewed in community.

**Comment by lolyu** [comment]
|PR description|link|note|
|-|-|-|
| subnet decap HLD | https://github.com/sonic-net/SONiC/pull/1657||

**Comment by zhangyanzhao** [comment]
code PR is not ready, move to backlog for future release

**Comment by zhangyanzhao** [comment]
HLD and code PRs are merged and close this tracking issue.
