### ISSUE TITLE
Kdump Remote SSH Config Enhancements

### ISSUE THREAD

**Issue by ridahanif96** [sonic-net/SONiC#1711]
This Feature enhance exisitng kdump feature  providing configuring dump remote feature using ssh in SONiC.  kdump is a feature of the Linux kernel that creates and stores a dump file in the event of a kernel crash. By using kdump ssh feature dump files can be stored remotely.

**Comment by ridahanif96** [comment]
@zhangyanzhao reference HLD https://github.com/sonic-net/SONiC/pull/1714 and code in review

**Comment by zhangyanzhao** [comment]
use https://github.com/sonic-net/SONiC/pull/1714 to track. close this issue.
