### ISSUE TITLE
Arista-7050CX3-32S-C32 Having Issues Recognizing Partition Table

### ISSUE THREAD

**Issue by VictorRascol** [sonic-net/SONiC#1799]
Arista-7050CX3-32S-C32 fails to recognize the file system after first boot.

SONiC Software Version: SONiC.20220531.27
SONiC OS Version: 11
Distribution: Debian 11.7
Kernel: 5.10.0-18-2-amd64
Build commit: 5e3b9620e9
Build date: Mon May  8 21:11:49 UTC 2023
Built by: cloudtest@e9f4a71ac000000

Platform: x86_64-arista_7050cx3_32s
HwSKU: Arista-7050CX3-32S-C32

The only difference between the problematic Arista 7050CX3's and the working CX3's are the IMG barcode numbers.

working switch: IMG-01237-03
non-working switch: IMG-00871-01

**Steps taken:**
Switch rebooted and entered Aboot.
umount /mnt/flash
mkfs.vfat /dev/mmcblk0
reboot
cp /mnt/usb1/sonic-aboot-broadcom-20220531.27.swi /mnt/flash
boot /mnt/flash/sonic-aboot-broadcom-20220531.27.swi
123.75: Cleaning flash content /mnt/flash
123.76: Installing image under /mnt/flash/image-20220531.27
123.76: Moving swi to a tmpfs
125.12: Extracting swi content
156.01: Extracting platform.tar.gz
156.08: Extracting dockerfs.tar.gz from swi
171.25: Unpacking dockerfs.tar.gz delayed to initrd because /mnt/flash is vfat or docker_inram is on
171.25: Remove installer
174.24: Generating boot-config, machine.conf and cmdline
174.40: Next reboot will use flash:image-20220531.27/.sonic-boot.swi
175.00: Kexecing[  174.832623] Starting new kernel
...
[    0.109980] AMD-Vi: Can not reserve memory region 0-80000 for mmio
[    0.183984] AMD-Vi: This is a BIOS bug. Please contact your hardware vendor
▒sfdisk: /dev/mmcblk0: does not contain a recognized partition table
mount: mounting /dev/mmcblk0 on /mnt/arista-firmware failed: Invalid argument
[    3.398818] overlayfs: filesystem on '/root/host/image-20220531.27/rw' not supported
mount: mounting root-overlay on /root failed: Invalid argument
[FAILED] Failed to start Security Auditing Service.
[    5.606680] rc.local[492]: + cat /etc/sonic/sonic_version.yml
[FAILED] Failed to start User Login Management.
[    5.681207] rc.local[493]: + grep build_version
[    5.831436] rc.local[495]: + sed -e s/build_version: //g;s/'//g
[    5.913459] rc.local[482]: + SONIC_VERSION=20220531.27
[FAILED] Failed to start User Login Management.
[    5.984998] rc.local[482]: + FIRST_BOOT_FILE=/host/image-20220531.27/platform/firsttime
[    6.180146] rc.local[482]: + SONIC_CONFIG_DIR=/host/image-20220531.27/sonic-config
[    6.272960] rc.local[482]: + SONIC_ENV_FILE=/host/image-20220531.27/sonic-config/sonic-environment
[    6.381041] rc.local[482]: + [ -d /host/image-20220531.27/sonic-config -a -f /host/image-20220531.27/sonic-config/sonic-environment ]
[FAILED] Failed to start Resets System Activity Logs.
[    6.536955] rc.local[482]: + logger SONiC version 20220531.27 starting up...
[FAILED] Failed to start User Login Management.
[    6.729084] rc.local[482]: + grub_installation_needed=
[FAILED] Failed to start User Login Management.
[    6.889135] rc.local[482]: + [ ! -e /host/machine.conf ]
[FAILED] Failed to start User Login Management.
[    7.057419] rc.local[482]: + . /host/machine.conf
[FAILED] Failed to start User Login Management.
[    7.205027] rc.local[482]: + aboot_version=6.1.10-14653765
[FAILED] Failed to start User Login Management.
[FAILED] Failed to start containerd container runtime.
[DEPEND] Dependency failed for Dock… Application Container Engine.
[    7.373046] rc.local[482]: + aboot_vendor=arista
[DEPEND] Dependency failed for database-chassis container.
[DEPEND] Dependency failed for Plat…opology configuration service.
[    7.665088] rc.local[482]: + aboot_platform=x86_64-arista_7050cx3_32s
[DEPEND] Dependency failed for Conf…ization and migration service.
[    7.825136] rc.local[482]: + aboot_machine=arista_7050cx3_32s
[DEPEND] Dependency failed for Upda…figuration based on minigraph.
[    8.201205] rc.local[482]: + aboot_arch=x86_64
[DEPEND] Dependency failed for gbsyncd service.
[    8.309015] rc.local[482]: + aboot_build_date=1970-01-01T00:00:00.000000000
[DEPEND] Dependency failed for BGP container.
[    8.540922] rc.local[482]: + program_console_speed
[DEPEND] Dependency failed for Update rsyslog configuration.
[    8.698177] rc.local[517]: + cat /proc/cmdline
[DEPEND] Dependency failed for ACMS container.
[    8.854857] kdump-tools[472]: Starting kdump-tools:
[DEPEND] Dependency failed for SONiC system health monitor.
[    9.004026] rc.local[518]: + grep -Eo console=ttyS[0-9]+,[0-9]+
[DEPEND] Dependency failed for Update interfaces configuration.
[    9.181433] kdump-tools[519]: no crashkernel= parameter in the kernel cmdline ...
[DEPEND] Dependency failed for Update CoPP configuration.
[    9.381191] kdump-tools[549]:  failed!
[DEPEND] Dependency failed for Proc…tilization data export daemon.
[    9.542202] rc.local[523]: + cut -d , -f2
[DEPEND] Dependency failed for TEAMD container.
[    9.706393] rc.local[482]: + speed=
[DEPEND] Dependency failed for Update hostname based on configdb.
[    9.840913] rc.local[482]: + [ -z  ]
[DEPEND] Dependency failed for Update logrotate configuration.
[    9.992908] rc.local[482]: + CONSOLE_SPEED=9600
[DEPEND] Dependency failed for syncd service.
[   10.159885] rc.local[530]: + grep agetty /lib/systemd/system/serial-getty@.service
[DEPEND] Dependency failed for Update NTP configuration.
[   10.338971] rc.local[531]: + grep keep-baud
[DEPEND] Dependency failed for Router advertiser container.
[   10.496913] rc.local[531]: ExecStart=-/sbin/agetty -o '-p -- [\\u'](file://u'/) --keep-baud 115200,57600,38400,9600 %I $TERM
[DEPEND] Dependency failed for Cont…lane ACL configuration daemon.
[   10.726117] rc.local[482]: + [ 0 = 0 ]
[DEPEND] Dependency failed for Container Manager watcher daemon.
[   10.889004] rc.local[482]: + sed -i s|\-\-keep\-baud .* %I| 9600 %I|g /lib/systemd/system/serial-getty@.service
[DEPEND] Dependency failed for switch state service.
[   11.122311] rc.local[536]: sed: couldn't open temporary file /lib/systemd/system/sedSSNqZI: Read-only file system
[DEPEND] Dependency failed for Database container.
[   11.339306] rc.local[482]: + systemctl daemon-reload
[DEPEND] Dependency failed for Reboot cause determination service.
[   11.488916] rc.local[482]: + [ -f /host/image-20220531.27/platform/firsttime ]
[DEPEND] Dependency failed for Moni…nd disable warmboot when done.
[   11.688919] rc.local[482]: + echo First boot detected. Performing first boot tasks...
[FAILED] Failed to start Arista early platform initialization.
[   11.901345] rc.local[482]: First boot detected. Performing first boot tasks...
[DEPEND] Dependency failed for Aris… late platform initialization.
[   12.096900] rc.local[482]: + [ -n x86_64-arista_7050cx3_32s ]
[DEPEND] Dependency failed for Arista platform daemon.
[   12.280901] rc.local[482]: + platform=x86_64-arista_7050cx3_32s
[DEPEND] Dependency failed for Arista Platform.
[   12.372988] rc.local[482]: + [ -d /host/old_config ]
[DEPEND] Dependency failed for Arista reboot cause processing.
[   12.592895] r[   12.697219] rc.local[482]: + [ -n  ]
[FAILED] Failed to start OpenBSD Secure Shell server.
[   12.721073] rc.local[482]: + touch /tmp/pending_config_initialization
[   12.946995] rc.local[578]: touch: cannot touch '/tmp/pending_config_initialization': Read-only file system
[   13.074385] rc.local[482]: + touch /tmp/notify_firstboot_to_platform
[   13.075996] rc.local[579]: touch: cannot touch '/tmp/notify_firstboot_to_platform': Read-only file system
[   13.078347] rc.local[482]: + [ ! -d /host/reboot-cause/platform ]
[   13.078687] rc.local[482]: + mkdir -p /host/reboot-cause/platform
[   13.080777] rc.local[482]: + [ -d /host/image-20220531.27/platform/x86_64-arista_7050cx3_32s ]
[   13.081316] rc.local[482]: + sync
[   13.081541] rc.local[482]: + [ -n  ]
[   13.081693] rc.local[482]: + mkdir -p /var/platform
[   13.083107] rc.local[582]: mkdir: cannot create directory ‘/var/platform’: Read-only file system
[   13.087459] rc.local[482]: + [ -f /etc/default/kdump-tools ]
[   13.087675] rc.local[482]: + sed -i -e s/__PLATFORM__/x86_64-arista_7050cx3_32s/g /etc/default/kdump-tools
[   13.089257] rc.local[583]: sed: couldn't open temporary file /etc/default/sedJoXwyh: Read-only file system
[   13.091039] rc.local[482]: + firsttime_exit
[   13.091312] rc.local[482]: + rm -rf /host/image-20220531.27/platform/firsttime
[   13.091514] rc.local[482]: + exit 0

**Comment by VictorRascol** [comment]
I should add the following:

The Aristas that ARE working show the flash on /dev/sda with ~32G. The Aristas I can't get sonic to boot on all have, /dev/mmcblk0 as the flash with a size of ~8G. They are both Arista-7050CX3-32S model switches.

**Comment by Staphylo** [comment]
You need to create partitions on your `/dev/mmcblk0` device using `fdisk`.
At minimum one partition that spans the whole disk which will be named `/dev/mmcblk0p1`
Your problem should go away once you've partitioned your device.

**Comment by VictorRascol** [comment]
Thanks @Staphylo. Issue was ultimately resolved by zeroing out the /dev/mmcblk0 device and THEN creating a partition and formatting it with mkfs.vfat. Trying to create the partition without zeroing out the disk resulted in SONiC
