### ISSUE TITLE
Inconsistency in YANG Model guidelines document

### ISSUE THREAD

**Issue by arista-hpandya** [sonic-net/SONiC#1802]
**Issue:**
We now use "sonic-net" instead of "Azure" in the namespace field of a yang model. However, this conflicted with the guidelines posted in the documentation.

**Files in discussion:**
doc/mgmt/SONiC_YANG_Model_Guidelines.md

**Solution:**
Replace Azure with sonic-net in YANG model guideline file

**Testing:**
Documentation change - not required

**Comment by arista-hpandya** [comment]
@wen587 Noticed you made the last few updates to the guidelines, hence tagging you here for a potential review of PR #1801

**Comment by wen587** [comment]
PR merged
