### ISSUE TITLE
TD3:PCIe firmware was not loaded

### ISSUE THREAD

**Issue by shanshri** [sonic-net/SONiC#907]
Hi All,

We are trying to bring up td3 with sonic os (latest code from github). We are seeing TD3 init errors with "PCIe firmware was not loaded" in the log.

 

BRCM SAI ver: [5.0.0.11], OCP SAI ver: [1.8.1], SDK ver: [sdk-6.5.21]

I am attaching the dmesg, sdk init logs and lspci output logs. Can you please help to identify what we are missing in sonic TD3 configuration?

Logs -

280:Nov 23 07:10:05.412439 tb63-host2-cimc INFO syncd#/supervisord: syncd <nounit>:ngknet_dev_ver_check: IOCTL failed on /dev/linux_ngknet#015
281:Nov 23 07:10:05.412439 tb63-host2-cimc INFO syncd#/supervisord: syncd <nounit>:bcma_sys_probe_ngbde: Unable to attach KNET driver#015
282:Nov 23 07:10:05.412439 tb63-host2-cimc INFO syncd#/supervisord: syncd Found 0 devices.#015
283:Nov 23 07:10:05.412439 tb63-host2-cimc INFO syncd#/supervisord: syncd DMA pool size: 33554432#015
284:Nov 23 07:10:05.414102 tb63-host2-cimc INFO syncd#/supervisord: syncd BDE dev 0 (PCI), Dev 0xb870, Rev 0x01, Chip BCM56870_A0, Driver BCM56870_A0#015
290:Nov 23 07:10:05.654223 tb63-host2-cimc INFO syncd#/supervisord: syncd SOC unit 0 attached to PCI device BCM56870_A0#015
291:Nov 23 07:10:05.662276 tb63-host2-cimc INFO syncd#/supervisord: syncd rc: unit 0 device BCM56870_A0#015
306:Nov 23 07:10:05.896956 tb63-host2-cimc INFO syncd#/supervisord: syncd 0:soc_trident3_chip_reset: TS_PLL locked on unit 0 using internal reference clock#015
307:Nov 23 07:10:06.037151 tb63-host2-cimc INFO syncd#/supervisord: syncd 0:soc_trident3_chip_reset: BS_PLL0 locked on unit 0 using internal reference clock#015
308:Nov 23 07:10:06.177596 tb63-host2-cimc INFO syncd#/supervisord: syncd 0:soc_trident3_chip_reset: BS_PLL1 locked on unit 0 using internal reference clock#015
356:Nov 23 07:10:06.688063 tb63-host2-cimc ERR syncd#syncd: :- sendApiResponse: api SAI_COMMON_API_CREATE failed in syncd mode: SAI_STATUS_FAILURE
357:Nov 23 07:10:06.688063 tb63-host2-cimc INFO syncd#/supervisord: syncd 0:soc_do_init: PCIe firmware was not loaded on unit 0#015
358:Nov 23 07:10:06.688063 tb63-host2-cimc INFO syncd#/supervisord: syncd INIT: Unable to initialize device: 0#015

Can someone please help in what might be wrong?

**Comment by YuriiHordynskyi** [comment]
Hello,
Looks like I have the same issue with the BCM56770_A0:
```
Nov  5 11:32:46.284836 sonic INFO syncd#/supervisord: syncd DMA pool size: 33554432#015
Nov  5 11:32:46.285004 sonic INFO syncd#/supervisord: syncd BDE dev 0 (PCI), Dev 0xb770, Rev 0x01, Chip BCM56770_A0, Driver BCM56770_A0#015
Nov  5 11:32:46.328903 sonic INFO pmon#supervisord 2022-11-05 11:32:46,327 INFO exited: ledd (exit status 1; not expected)
Nov  5 11:32:46.465698 sonic INFO syncd#/supervisord: syncd SOC unit 0 attached to PCI device BCM56770_A0#015
Nov  5 11:32:47.207593 sonic INFO lldp#supervisord 2022-11-05 11:32:47,206 INFO spawned: 'start' with pid 18
Nov  5 11:32:47.208605 sonic INFO lldp#supervisord 2022-11-05 11:32:47,207 INFO success: start entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Nov  5 11:32:47.480009 sonic ERR syncd#syncd: [none] SAI_API_SWITCH:platform_process_command:436 Platform command "init soc" failed, rc = -1.
Nov  5 11:32:47.480431 sonic CRIT syncd#syncd: [none] SAI_API_SWITCH:platformInit:2009 initialization command "init soc" failed, rc = -1 (Internal error).
Nov  5 11:32:47.480850 sonic CRIT syncd#syncd: [none] SAI_API_SWITCH:sai_driver_init:445 Error initializing driver, rc = -1.
Nov  5 11:32:47.481120 sonic ERR swss#orchagent: :- create: create status: SAI_STATUS_FAILURE
Nov  5 11:32:47.481120 sonic ERR swss#orchagent: :- main: Failed to create a switch, rv:-1
Nov  5 11:32:47.481404 sonic CRIT syncd#syncd: [none] SAI_API_SWITCH:brcm_sai_create_switch:1134 initializing SDK failed with error Operation failed (0xfffffff5).
Nov  5 11:32:47.481539 sonic ERR syncd#syncd: :- sendApiResponse: api SAI_COMMON_API_CREATE failed in syncd mode: SAI_STATUS_FAILURE
Nov  5 11:32:47.481648 sonic NOTICE swss#orchagent: :- uninitialize: begin
Nov  5 11:32:47.481648 sonic INFO syncd#/supervisord: syncd 0:soc_do_init: PCIe firmware was not loaded on unit 0#015
Nov  5 11:32:47.481648 sonic INFO syncd#/supervisord: syncd INIT: Unable to initialize device: 0#015
```

**Comment by shanshri** [comment]
Check if you are following the proper sequence to bring td3 out of reset. Mine was solved with that.

**Comment by YuriiHordynskyi** [comment]
Thank you for your advice. I will double-check.

**Comment by shivanangi** [comment]
Where you able to fix the issue?

**Comment by YuriiHordynskyi** [comment]
Not yet. Still in progress.

**Comment by YuriiHordynskyi** [comment]
> Check if you are following the proper sequence to bring td3 out of reset. Mine was solved with that.

@shivanangi, Did you mean to follow the sequence?
![Screenshot from 2022-11-15 14-02-05](https://user-images.githubusercontent.com/48444208/201918235-f27cf6ce-d7b1-4995-9b52-3dcf3eccd222.png)
```
1'b1: mHost0 comes out of reset and begins executing code based on the setting of the
BOOT_DEV[2:0] strap signals.
```
