### ISSUE TITLE
[new feature request] Port-security

### ISSUE THREAD

**Issue by salvadorb** [sonic-net/SONiC#957]
Hi SONIC community,
I hope you're doing great. I was wondering if it would be possible to propose a new feature "Port-security", which is very important for Internet Exchanges Points. The most-popular feature within port-security is to set a maximum number of MAC addresses per interface, if the number of MAC addresses in the interface exceeds the defined limit the port goes to errdisable (basically disable the interface). Usually, after a couple of minutes, the recovery mechanism will re-enable the interface and if the number of learned MAC addresses from the interface keeps within the threshold the interface works fine, if it exceeds the threshold will trigger an errdisable action once again. 

This is important for almost all switches connected to a third party in Internet Exchanges, in this case, member ports. Since it's a very important good practice to only allow connections directly to routers (or switch's interface in routing mode), but no switches in L2 mode, cause it could (and usually do) create a lot of problems.

Best regards,

**Comment by salvadorb** [comment]
Here is an example: https://www.arista.com/en/um-eos/eos-data-transfer#xx1136656

**Comment by zhangyanzhao** [comment]
If you want to contribute one feature to next SONiC release, please check https://groups.google.com/g/sonicproject/c/ihKlgY5-gqc
