### ISSUE TITLE
SONiC web page is not available or has changed

### ISSUE THREAD

**Issue by gkunz** [sonic-net/SONiC#995]
The SONiC webpage linked from the repository (http://azure.github.io/SONiC/) is not available and throws a 404. Has the page moved elsewhere or will there be a new page in the context of moving SONiC to LF?

Thank you!

**Comment by TildenWinston** [comment]
New URL seems to be http://sonic-net.github.io/SONiC/

**Comment by gkunz** [comment]
Thank you @TildenWinston!
